### PR TITLE
Python code rename

### LINKED ISSUE #222: (Playground) Student tries to rename the file of code
**Describe the bug**
The rename option in the playground does not work properly

**To Reproduce**
1. Start writing python code in the playground
2. tap on the three-dot menu
3. Tap on rename
4. Rename option does not work
5. The menu disappears

**Expected behaviour**
Popup is shown where the file can be renamed

**Screencast**
https://drive.google.com/file/d/1elZXbcNCu0uw3cla0KL_wlZuehtPIy6-/view

**Refer Sheet:**
TestCases for Playground (app), Test Case 8.1

### PR DESCRIPTION
**Pull request by maheshpandey04**
issue resolved #222

### CODE REVIEW

File: chat/src/main/java/org/navgurukul/chat/features/home/room/list/RoomListFragment.kt [hunk 1]
```diff
@@ -114,6 +116,15 @@ class RoomListFragment : BaseFragment(), RoomSummaryController.Listener {
 
 
     private fun handleSelectRoom(event: RoomListViewEvents.SelectRoom) {
+        if(event.roomSummary.roomId=="!mpKUsizojzHSvioqKx:navgurukul.org"){
```
Comment (damanpreet97) [inline chat/src/main/java/org/navgurukul/chat/features/home/room/list/RoomListFragment.kt:119]: I think this entire 'if' block is for test. pls remove it

File: python/src/main/java/org/navgurukul/playground/editor/PythonEditorActivity.kt [hunk 2]
```diff
@@ -34,6 +37,17 @@ class PythonEditorActivity : AppCompatActivity() {
     override fun onCreateOptionsMenu(menu: Menu?): Boolean {
         val inflater: MenuInflater = menuInflater
         inflater.inflate(R.menu.python_playground_menu, menu)
+        for (i in 0 until menu!!.size()) {
```
Comment (damanpreet97) [inline python/src/main/java/org/navgurukul/playground/editor/PythonEditorActivity.kt:40]: instead of ' menu!! ' you should use menu?.let{ }
This ensures that the code won't run if the menu is null. However, in the earlier case it could crash.
Also doing after this you wouldn't require to use ' menu!! ' in the below code as 'it' would be available in the scope

**Review by damanpreet97 — CHANGES_REQUESTED** [review]

**Review by damanpreet97 — APPROVED** [review]
