### PR TITLE
Fixes/aashish

### LINKED ISSUE #59: Login Flow Changes
When we login, clicking on "Sign up" doesn't change the screen. Following change is to be made:

In the main screen, instead of "Login Here", say : "Connect With Email"
And directly open the email prompt.

### PR DESCRIPTION
**Pull request by aashish-aadarsh**
Fixed #59 and #55

### CODE REVIEW

**Comment by aashish-aadarsh** [comment]
Please accept master branch changes for resolving conflict.

File: app/src/main/java/org/merakilearn/ui/onboarding/WelcomeFragment.kt [hunk 1]
```diff
@@ -74,6 +80,63 @@ class WelcomeFragment : BaseFragment() {
...
+            val task =
+                GoogleSignIn.getSignedInAccountFromIntent(data)
+            handleSignInResult(task)
+        }
+    }
+
+    private fun handleSignInResult(completedTask: Task<GoogleSignInAccount>) {
+        try {
+            val account = completedTask.getResult(ApiException::class.java)
+            logOutSelectedAccount(account)
```
Comment (suhaibroomy) [inline app/src/main/java/org/merakilearn/ui/onboarding/WelcomeFragment.kt:110]: why are we signing out from the account in case of sign in?

File: app/src/main/java/org/merakilearn/ui/onboarding/WelcomeFragment.kt [hunk 2]
```diff
@@ -74,6 +80,63 @@ class WelcomeFragment : BaseFragment() {
...
+        } catch (e: ApiException) {
+            Log.e(LoginFragment.TAG, "signInResult:failed code=", e)
+            toast(getString(R.string.unable_to_sign))
+        }
+    }
+
+    private fun logOutSelectedAccount(account: GoogleSignInAccount) {
+        mGoogleSignInClient?.signOut()?.addOnSuccessListener {
+            viewModel.idToken.value = account.idToken
```
Comment (suhaibroomy) [inline app/src/main/java/org/merakilearn/ui/onboarding/WelcomeFragment.kt:119]: liveData should be used to communicate from viewModel to view not the other way around. This should be done by calling a method on viewModel or better use already implemented actions for the sake of consistency

File: app/src/main/java/org/merakilearn/ui/onboarding/WelcomeFragment.kt [hunk 3]
```diff
@@ -74,6 +80,63 @@ class WelcomeFragment : BaseFragment() {
...
+            observeFetchingBackendToken()
+        }
+    }
+
+    private fun observeFetchingBackendToken() {
+        toggleProgressBarVisibility(View.VISIBLE)
+        viewModel.loginResult.observe(this, Observer {
```
Comment (suhaibroomy) [inline app/src/main/java/org/merakilearn/ui/onboarding/WelcomeFragment.kt:126]: Observers should not be registered multiple times. They should be register once. If we register on some click event, they will be registered everytime we click on it

File: app/src/main/java/org/merakilearn/ui/onboarding/WelcomeFragment.kt [hunk 4]
```diff
@@ -74,6 +80,63 @@ class WelcomeFragment : BaseFragment() {
...
+            toggleProgressBarVisibility(View.GONE)
+            if (it) {
+                MainActivity.launch(requireContext())
```
Comment (suhaibroomy) [inline app/src/main/java/org/merakilearn/ui/onboarding/WelcomeFragment.kt:129]: Better use events and state here. Also instead on calling launch, we can use navigator which already has a method for intent of home screen. Maybe add a method for launching the same in naviagator or just use the intent

File: app/src/main/java/org/merakilearn/ui/onboarding/WelcomeFragment.kt [hunk 5]
```diff
@@ -74,6 +80,63 @@ class WelcomeFragment : BaseFragment() {
...
+            } else
+                toast(getString(R.string.email_already_used))
```
Comment (suhaibroomy) [inline app/src/main/java/org/merakilearn/ui/onboarding/WelcomeFragment.kt:131]: There is an event for showing toast, use that instead

File: app/src/main/java/org/merakilearn/ui/onboarding/WelcomeFragment.kt [hunk 6]
```diff
@@ -2,16 +2,24 @@ package org.merakilearn.ui.onboarding
 
 import android.content.Context
 import android.os.Build
+import android.content.Intent
 import android.os.Bundle
+import android.util.Log
```
Comment (suhaibroomy) [inline app/src/main/java/org/merakilearn/ui/onboarding/WelcomeFragment.kt:7]: Use timber instead of logs

File: app/src/main/java/org/merakilearn/ui/onboarding/WelcomeFragment.kt (hunk 1 above)
Comment (aashish-aadarsh) [reply app/src/main/java/org/merakilearn/ui/onboarding/WelcomeFragment.kt:110]: Google save the account selected, and when the user log out from application and try to login again, it doesn't prompt for email selection again and it select the earlier one by default. This behaviour wasn't desired by the team so need to do

File: app/src/main/java/org/merakilearn/ui/onboarding/WelcomeFragment.kt (hunk 6 above)
Comment (aashish-aadarsh) [reply app/src/main/java/org/merakilearn/ui/onboarding/WelcomeFragment.kt:7]: Any specific reason for using timber ?

File: app/src/main/java/org/merakilearn/ui/onboarding/WelcomeFragment.kt (hunk 4 above)
Comment (aashish-aadarsh) [reply app/src/main/java/org/merakilearn/ui/onboarding/WelcomeFragment.kt:129]: Launch is actually using intent only which is defined in activity companion object

File: app/src/main/java/org/merakilearn/ui/onboarding/WelcomeFragment.kt (hunk 5 above)
Comment (aashish-aadarsh) [reply app/src/main/java/org/merakilearn/ui/onboarding/WelcomeFragment.kt:131]: Will do that

File: app/src/main/java/org/merakilearn/ui/onboarding/WelcomeFragment.kt (hunk 2 above)
Comment (aashish-aadarsh) [reply app/src/main/java/org/merakilearn/ui/onboarding/WelcomeFragment.kt:119]: Since the live data observer activate on condition , so Transformation.switchMap is used. To do that, above code is written

File: app/src/main/java/org/merakilearn/ui/onboarding/WelcomeFragment.kt (hunk 5 above)
Comment (aashish-aadarsh) [reply app/src/main/java/org/merakilearn/ui/onboarding/WelcomeFragment.kt:131]: BTW, importance of using event to trigger a toast ??

File: app/src/main/java/org/merakilearn/ui/onboarding/WelcomeFragment.kt (hunk 3 above)
Comment (aashish-aadarsh) [reply app/src/main/java/org/merakilearn/ui/onboarding/WelcomeFragment.kt:126]: Will remove from click event

File: app/src/main/java/org/merakilearn/ui/onboarding/WelcomeFragment.kt (hunk 5 above)
Comment (suhaibroomy) [reply app/src/main/java/org/merakilearn/ui/onboarding/WelcomeFragment.kt:131]: To move logic inside viewModel. View should be as dumb as possible, viewModel should be the one making these decisions

File: app/src/main/java/org/merakilearn/ui/onboarding/WelcomeFragment.kt (hunk 4 above)
Comment (suhaibroomy) [reply app/src/main/java/org/merakilearn/ui/onboarding/WelcomeFragment.kt:129]: Yes still Welcome Fragment is using Main Activity explicitly. Its better if we use navigator for navigation in all new code we write atleast as it makes it easy for us to track all navigations or to make changes from a single source.

File: app/src/main/java/org/merakilearn/ui/onboarding/WelcomeFragment.kt (hunk 2 above)
Comment (suhaibroomy) [reply app/src/main/java/org/merakilearn/ui/onboarding/WelcomeFragment.kt:119]: I guess we can remove switch map, it seems unnecessary. To use live data to pass some values to viewModel is not a good approach.

File: app/src/main/java/org/merakilearn/ui/onboarding/WelcomeFragment.kt (hunk 1 above)
Comment (suhaibroomy) [reply app/src/main/java/org/merakilearn/ui/onboarding/WelcomeFragment.kt:110]: We should not log out instead try clearing the default account. Logging user out means we won't be able to access token for fetching information. For reference take a loot at this - https://stackoverflow.com/a/39814778/4260786

Comment (aashish-aadarsh) [reply app/src/main/java/org/merakilearn/ui/onboarding/WelcomeFragment.kt:110]: I have implemented this earlier but was causing crash ! I'll try again and let you know

File: app/src/main/java/org/merakilearn/ui/onboarding/WelcomeFragment.kt (hunk 2 above)
Comment (aashish-aadarsh) [reply app/src/main/java/org/merakilearn/ui/onboarding/WelcomeFragment.kt:119]: How can we then do ? I saw same approach in the YouTube video, I shared. Please suggest me some other way then

File: app/src/main/java/org/merakilearn/ui/onboarding/WelcomeFragment.kt (hunk 5 above)
Comment (aashish-aadarsh) [reply app/src/main/java/org/merakilearn/ui/onboarding/WelcomeFragment.kt:131]: Understood ! Will implement this

File: app/src/main/java/org/merakilearn/ui/onboarding/WelcomeFragment.kt (hunk 6 above)
Comment (suhaibroomy) [reply app/src/main/java/org/merakilearn/ui/onboarding/WelcomeFragment.kt:7]: It doesn't print logs in production and also since we are already using it in chatSDK so its not extra burden

File: app/src/main/java/org/merakilearn/ui/onboarding/WelcomeFragment.kt (hunk 4 above)
Comment (aashish-aadarsh) [reply app/src/main/java/org/merakilearn/ui/onboarding/WelcomeFragment.kt:129]: I tried to implement this referring to method implemented already. I got confused in between. It would be great, if you can help with this one. It might give me insights bon MVI

File: app/src/main/java/org/merakilearn/ui/onboarding/WelcomeFragment.kt (hunk 2 above)
Comment (suhaibroomy) [reply app/src/main/java/org/merakilearn/ui/onboarding/WelcomeFragment.kt:119]: Is it okay if I make these changes and make a commit??

**Review by suhaibroomy — APPROVED** [review]
